en:
  how_it_works: Looking for that new sweater for the season? Sign up, fill out a profile, and we take care of the rest!
en_GB:
  how_it_works: Chuffed for a new jumper for the season? Sign up, fill out a profile, and we take care of the rest!
